# Generated by Django 5.2.17 on 2026-08-13 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название коэффициента')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Коэффициент сложности бронирования',
                'verbose_name_plural': 'Коэффициенты сложности бронирования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArmorElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название элемента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга бронирования элемента',
                'verbose_name_plural': 'Услуги бронирования элементов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ArmorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('package_type', models.CharField(choices=[('standard', 'Стандарт'), ('standard_plus', 'Стандарт+'), ('premium', 'Премиум'), ('premium_plus', 'Премиум+')], max_length=20, unique=True, verbose_name='Тип пакета')),
                ('description', models.TextField(verbose_name='Состав пакета')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена (₽)')),
            ],
            options={
                'verbose_name': 'Пакет бронирования',
                'verbose_name_plural': 'Пакеты бронирования',
                'ordering': ['base_price'],
            },
        ),
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Умножается на базовую цену услуги', max_digits=4, verbose_name='Коэффициент сложности')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузовов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TintCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название коэффициента')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Значение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Коэффициент сложности тонировки',
                'verbose_name_plural': 'Коэффициенты сложности тонировки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TintFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('film_type', models.CharField(choices=[('korean', 'Корейская (Spectroll)'), ('american', 'Американская (SunControl)'), ('athermal', 'Атермальная')], max_length=20, unique=True, verbose_name='Тип')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('coefficient', models.DecimalField(decimal_places=2, default=1.0, help_text='Умножается на базовую цену тонировки. Например: 1.5 для дорогой плёнки.', max_digits=4, verbose_name='Коэффициент стоимости плёнки')),
            ],
            options={
                'verbose_name': 'Плёнка для тонировки',
                'verbose_name_plural': 'Плёнки для тонировки',
                'ordering': ['film_type'],
            },
        ),
        migrations.CreateModel(
            name='TintService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовая цена (₽)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга тонировки',
                'verbose_name_plural': 'Услуги тонировки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('armor_coefficient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_models_armor', to='services.armorcoefficient', verbose_name='Коэффициент бронирования')),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.bodytype', verbose_name='Тип кузова')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='services.carbrand', verbose_name='Марка')),
                ('tint_coefficient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_models_tint', to='services.tintcoefficient', verbose_name='Коэффициент тонировки')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['brand__name', 'name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FilmTintPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.PositiveSmallIntegerField(verbose_name='Процент светопропускаемости')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percents', to='services.tintfilm', verbose_name='Плёнка')),
            ],
            options={
                'verbose_name': 'Процент светопропускаемости плёнки',
                'verbose_name_plural': 'Проценты светопропускаемости плёнок',
                'ordering': ['film', 'percent'],
                'unique_together': {('film', 'percent')},
            },
        ),
    ]
