# Generated by Django 5.2.17 on 2026-08-13 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('meter', 'Метр'), ('roll', 'Рулон'), ('piece', 'Штука'), ('liter', 'Литр')], default='meter', max_length=20, verbose_name='Единица измерения')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущий остаток')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальный запас')),
                ('price_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за единицу (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата списания')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumptions', to='bookings.booking', verbose_name='Связанная запись')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Расход материала',
                'verbose_name_plural': 'Расходы материалов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая стоимость (₽)')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='Поставщик')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата прихода')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='inventory.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Приход материала',
                'verbose_name_plural': 'Приходы материалов',
                'ordering': ['-created_at'],
            },
        ),
    ]
