# Generated by Django 5.2.17 on 2026-08-13 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('tint', 'Тонировка'), ('armor', 'Бронирование')], max_length=10, verbose_name='Тип услуги')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('remove_old_tint', models.BooleanField(default=False, verbose_name='Снять старую тонировку')),
                ('booking_date', models.DateField(verbose_name='Дата')),
                ('booking_time', models.TimeField(verbose_name='Время')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Базовая цена')),
                ('discount_applied', models.DecimalField(decimal_places=0, default=0, max_digits=3, verbose_name='Применённая скидка (%)')),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Итоговая цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('admin_note', models.TextField(blank=True, verbose_name='Заметка администратора')),
                ('armor_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.armorpackage', verbose_name='Пакет бронирования')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='accounts.usercar', verbose_name='Автомобиль')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('tint_film_percent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.filmtintpercent', verbose_name='Плёнка и процент')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-booking_date', '-booking_time'],
                'indexes': [models.Index(fields=['booking_date', 'booking_time'], name='bookings_bo_booking_fa13ed_idx'), models.Index(fields=['status'], name='bookings_bo_status_233e96_idx')],
            },
        ),
    ]
